name: Sello_1991
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Victoria Final" > sello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: APK_Sello_1991
          path: sello.txt
