name: Sincronia_Vasto_1700
on: [push]
jobs:
  ejecucion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sello 1991
        run: echo "Soberanía Técnica: Finca 5-25533 en línea"
