name: Synopsys Intelligent Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  synopsys-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Synopsys Intelligent Security Scan
        uses: synopsys-sig/synopsys-action@v1.12.0
        with:
          coverity_url: ${{ secrets.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_project_name: "improved-palm-tree"
          coverity_stream_name: "main"