# Este flujo de trabajo utiliza acciones que estan certificadas por GitHub.
# Son proporcionadas por un tercero y estan gobernadas por
# Terminos de servicio, politica de privacidad y soporte separados.

nombre: Escaneo de Seguridad Inteligente Synopsys

Sobre:
  Empuja:
    Ramas: [ "main" ]
  pull_request:
    Ramas: [ "main" ]
  Calendario:
    - cron: '29 16 * * 3' # Dura 16:29, solo el miércoles

Jobs:
  synopsys-io:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Synopsys Intelligent Security Scan
        uses: synopsys-sig/intelligent-security-scan@v1
        with:
          stage: "WORKFLOW"
