name: Synopsys Intelligent Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  synopsys-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Synopsys Intelligent Security Scan
        uses: synopsys-sig/synopsys-action@v1.12.0
        with:
          coverity_url: "PON_AQUI_LA_URL_REAL_DE_TU_SERVIDOR"
          coverity_user: "PON_AQUI_TU_USUARIO"
          coverity_passphrase: "PON_AQUI_TU_PASSWORD"
          coverity_project_name: "improved-palm-tree"
          coverity_stream_name: "main"